name: Code Style

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 src/
